### PR TITLE
Packaging

### PR DESCRIPTION
**Pull request by thekad**
RPM/Zuul configuration to package this project as an RPM

Depends-On: https://softwarefactory-project.io/r/c/dci-jobs/+/29071

### CODE REVIEW

**Comment by thekad** [comment]
@fredericlepied PTAL, also not sure if zuul would pick the configuration up now or until after it's been merged

**Review by fredericlepied — CHANGES_REQUESTED** [review]
I cannot make it compile the rpm locally using build_rpm.sh. How did you do it?

**Comment by fredericlepied** [comment]
are you going to adapt the zuul job as it will not work like this?

**Comment by thekad** [comment]
> are you going to adapt the zuul job as it will not work like this?

The zuul job only looks at the .spec file and sources listed in the root dir, the rpm directory is only for you/me to try building the RPM

**Comment by thekad** [comment]
Depends-On: https://softwarefactory-project.io/r/c/dci-jobs/+/29071

**Comment by thekad** [comment]
recheck

**Comment by thekad** [comment]
recheck

**Comment by thekad** [comment]
recheck

**Review by fredericlepied — APPROVED** [review]

**Pull request merged**
